### ISSUE TITLE
Dragging pseudo-nodes from a dock

### ISSUE THREAD

**Issue by Ni55aN** [retejs/dock-plugin#1]

**Comment by Ni55aN** [comment]
![Opera Snapshot_2019-03-24_173346_127 0 0 1](https://user-images.githubusercontent.com/8259641/54881698-143c5700-4e5b-11e9-880d-e884f5b5135a.png)

**Comment by akshayred** [comment]
Where can I find code or working example for this?

**Comment by Ni55aN** [comment]
@akshayred 
Code: https://github.com/retejs/rete.js.org/tree/master/src/components/Examples/list/dock
Example: https://rete.js.org/#/examples/dock

**Comment by akshayred** [comment]
@Ni55aN Thanks for your quick response. I checked the code and example.
But what I am implementing is by using html and Nodejs.
So when I added https://cdn.jsdelivr.net/npm/rete-dock-plugin@0.1.1/build/dock-plugin.common.min.js
to my html file, I am getting error ReferenceError: exports in not defined.

**Comment by Ni55aN** [comment]
This minified bundle by JsDelivr has CommonJs format (for Node.js, not browser). You need a UMD - [this one](https://cdn.jsdelivr.net/npm/rete-dock-plugin@0.1.1/build/dock-plugin.min.js)

Then you must use it as follows:
```js
editor.use(DockPlugin.default, ...
```

**Comment by Ni55aN** [comment]
By the way, I always advise to use ES modules if you have the opportunity to use a bundler. 
UMDs are only useful when you want to use it on Codepen, for example

**Comment by akshayred** [comment]
@Ni55aN Thanks for your inputs. But what I am trying to do here is, I am building a drupal 8 module and I don't want to have a dependency of Nodejs for that module. So when someone will use that module it should be just easy enabling that module and it should work. Do you think this could have some problem?

**Comment by Ni55aN** [comment]
> Do you think this could have some problem?

Its harder to manage dependencies in this way. In addition, UMD modules have polyfills, which leads to an increase in the size of each bundle by about 5 KB
