### ISSUE TITLE
Horizontal and vertical text menu

### ISSUE THREAD

**Issue by Ni55aN** [retejs/dock-plugin#2]

**Comment by Hatead1** [comment]
А может вообще разделить контекстное меню и главное? Как ни крути, а получается два плагина, так пусть будет независимый с контекстным и универсальный с двумя типами меню

**Comment by Ni55aN** [comment]
> контекстное меню и главное?

Главное, в смысле Док меню?

> универсальный с двумя типами меню

контекстное и прикрепленное? Они мало чем похожи (во втором не нужен delay и координаты), имхо лучше не переплетать функционал

**Comment by Hatead1** [comment]
Я имел ввиду context-menu-plugin оставить только для контекстного (Delete/Clone), новое сделать универсальным, но там действительно мало общего, согласен. Или вообще их разделить совсем, context, float и dock, а то получается, что при установке cmp и dock будет два главных меню :)

**Comment by Ni55aN** [comment]
All types of menu placement can be defined in CSS (example in the Readme)
