### ISSUE TITLE
Version 0.2.1 is not available to install with new Rete.js versions

### ISSUE THREAD

**Issue by sfe-efficy** [retejs/dock-plugin#20]
When I try to install the last "rete-dock-plugin" (v.0.2.1) it's complaining if the Rete.js version is not 1.3.0:

npm ERR! Could not resolve dependency:
npm ERR! peer rete@"1.3.0" from rete-dock-plugin@0.2.1
npm ERR! node_modules/rete-dock-plugin
npm ERR!   rete-dock-plugin@"0.2.1" from the root project

The problem comes from package.json at line 23.

https://github.com/retejs/dock-plugin/blob/master/package.json#L23

In my case, I selected to use the previous one.

**Comment by melodysium** [comment]
Seconding this issue, it would be nice to update this module's `package.json` to allow `"rete": "^1.3.0"` (as other plugins like [connection-plugin](https://github.com/retejs/connection-plugin/blob/master/package.json) do) and not just `"rete": "1.3.0"`
