### ISSUE TITLE
How can we have a drag drop functionality for nodes?

### ISSUE THREAD

**Issue by akshayred** [retejs/dock-plugin#3]
So I want to list all node types in a left sidebar and user should be able to drag and drop nodes in the editor. How can we make that happen?

**Comment by Ni55aN** [comment]
https://github.com/retejs/dock-plugin/issues/1

**Comment by Ni55aN** [comment]
README contains an example from the bottom dock menu. You can define your styles to place a list of nodes as you want

https://github.com/retejs/dock-plugin/issues/1#issuecomment-475970247
