### ISSUE TITLE
Implement dockmenu in react

### ISSUE THREAD

**Issue by mohandass-pat** [retejs/dock-plugin#5]
Hi I'm trying to implement dock menu in react. How to implement that in react? Any examples over that would be great. Thanks in advance :)

**Comment by Ni55aN** [comment]
Like [this](https://codepen.io/Ni55aN/pen/XvjmeZ)?

**Comment by mohandass-pat** [comment]
Yes. Thanks :)

**Comment by hanibhat** [comment]
Is it possible to arbitrarily add different nodes in the dock? For example, I'm working on a project that would have certain nodes already rendered when the component is loaded, but the user should also have a list (dock menu) of other nodes that could be added to the editor.
